[build]
  command = "npm ci && npm run build:frontend"
  publish = "client/build"
  functions = "server"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

# Optional: set environment here or in Netlify UI
# [build.environment]
#   NODE_VERSION = "18"
#   REACT_APP_API_BASE_URL = "https://your-backend.example.com"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chat"
  status = 200
  force = true


